### ISSUE TITLE
Building curl on ancient centos box

### ISSUE THREAD

**Issue by JasonDictos** [ruslo/intsizeof#1]
Hi was trying to use hunter to update our dependencies on one of our very old centos boxes, encountered this error:

Scanning dependencies of target libcurl
[  2%] Building C object lib/CMakeFiles/libcurl.dir/timeval.c.o
[  2%] Building C object lib/CMakeFiles/libcurl.dir/base64.c.o
[  3%] Building C object lib/CMakeFiles/libcurl.dir/hostip.c.o
[  3%] Building C object lib/CMakeFiles/libcurl.dir/file.c.o
[  3%] Building C object lib/CMakeFiles/libcurl.dir/progress.c.o
[  4%] Building C object lib/CMakeFiles/libcurl.dir/formdata.c.o
[  5%] Building C object lib/CMakeFiles/libcurl.dir/sendf.c.o
[  6%] Building C object lib/CMakeFiles/libcurl.dir/http.c.o
[  7%] Building C object lib/CMakeFiles/libcurl.dir/cookie.c.o
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/timeval.h:30,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/timeval.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/hostip.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/base64.c:25:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/progress.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
[  8%] Building C object lib/CMakeFiles/libcurl.dir/url.c.o
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/formdata.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/cookie.c:83:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
[  8%] Building C object lib/CMakeFiles/libcurl.dir/ldap.c.o
[  9%] Building C object lib/CMakeFiles/libcurl.dir/version.c.o
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/http.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
[ 10%] Building C object lib/CMakeFiles/libcurl.dir/mprintf.c.o
[ 10%] Building C object lib/CMakeFiles/libcurl.dir/ftp.c.o
gmake[5]: *** [lib/CMakeFiles/libcurl.dir/timeval.c.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
gmake[5]: *** Waiting for unfinished jobs....[ 11%] Building C object lib/CMakeFiles/libcurl.dir/dict.c.o

[ 12%] Building C object lib/CMakeFiles/libcurl.dir/speedcheck.c.o
gmake[5]: *** Waiting for unfinished jobs....
gmake[5]: *** Waiting for unfinished jobs....
gmake[5]: In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/sendf.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
*** Waiting for unfinished jobs....
gmake[5]: *** Waiting for unfinished jobs....
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/url.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/dict.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/mprintf.c:38:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/speedcheck.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
[ 13%] Building C object lib/CMakeFiles/libcurl.dir/if2ip.c.o
gmake[5]: *** Waiting for unfinished jobs....
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/ldap.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
[ 14%] Building C object lib/CMakeFiles/libcurl.dir/getenv.c.o
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
gmake[5]: *** Waiting for unfinished jobs....
[ 15%] Building C object lib/CMakeFiles/libcurl.dir/escape.c.o
gmake[5]: *** Waiting for unfinished jobs....
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/if2ip.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/escape.c:26:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/version.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
gmake[5]: *** [lib/CMakeFiles/libcurl.dir/dict.c.o] Error 1
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/ftp.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/file.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
In file included from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:3:0,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/curl_setup.h:41,
                 from /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL/Source/lib/getenv.c:23:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
gmake[5]: *** [lib/CMakeFiles/libcurl.dir/mprintf.c.o] Error 1
gmake[4]: *** [lib/CMakeFiles/libcurl.dir/all] Error 2
gmake[3]: *** [all] Error 2
gmake[2]: *** [CURL-Release-prefix/src/CURL-Release-stamp/CURL-Release-build] Error 2
gmake[1]: *** [CMakeFiles/CURL-Release.dir/all] Error 2
gmake: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Build/CURL
[hunter ** FATAL ERROR **] [Directory:/home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/projects/CURL]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_download.cmake:648 (hunter_fatal_error)
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/projects/CURL/hunter.cmake:81 (hunter_download)
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:15 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/jason/backupagentapp/libbrt/common/_build/CMakeFiles/CMakeOutput.log".
~/backupagentapp/libbrt/common/_build ~/backupagentapp/libbrt/common
make: *** No rule to make target `install'.  Stop.

**Comment by ruslo** [comment]
Is the error the same if you try:
```cmake
hunter_add_package(Intsizeof)
find_package(Intsizeof CONFIG REQUIRED)
```

and

```cpp
#include <intsizeof.h>
```
?

**Comment by JasonDictos** [comment]
[jason@localhost test]$ cmake . 
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/jason/.hunter
-- [hunter] [ Hunter-ID: 9e10359 | Toolchain-ID: 45e2ab9 | Config-ID: 15c25e7 ]

[hunter ** INTERNAL **] Project 'Intsizeof' not found
[hunter ** INTERNAL **] [Directory:/home/jason/test]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_get_project_files_to_load.cmake:68 (hunter_internal_error)
  /home/jason/.hunter/_Base/Download/Hunter/0.19.238/9e10359/Unpacked/cmake/modules/hunter_add_package.cmake:40 (hunter_get_project_files_to_load)
  CMakeLists.txt:13 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/home/jason/test/CMakeFiles/CMakeOutput.log".
[jason@localhost test]$

**Comment by JasonDictos** [comment]
cmake_minimum_required(VERSION 3.10.2 FATAL_ERROR)

set(HUNTER_TLS_VERIFY off)

include(cmake/HunterGate.cmake)
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.238.tar.gz"
        SHA1 "9e103596184adb7206430047375a07eb1fa6a9b4"
)

project(BrtCommon)

hunter_add_package(Intsizeof)
find_package(Intsizeof CONFIG REQUIRED)
~

**Comment by JasonDictos** [comment]
Ok, got it working with 'lowercase' intsizeof:

Scanning dependencies of target Test
make[2]: Leaving directory `/home/jason/test'
make -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
make[2]: Entering directory `/home/jason/test'
[ 50%] Building C object CMakeFiles/Test.dir/test.c.o
/usr/local/bin/cc  -I/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include   -o CMakeFiles/Test.dir/test.c.o   -c /home/jason/test/test.c
In file included from /home/jason/test/test.c:1:0:
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:213:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include/intsizeof.h:278:3: error: #error "Please report error to https://github.com/ruslo/intsizeof/issues"
 # error "Please report error to https://github.com/ruslo/intsizeof/issues"
   ^
make[2]: *** [CMakeFiles/Test.dir/test.c.o] Error 1
make[2]: Leaving directory `/home/jason/test'
make[1]: *** [CMakeFiles/Test.dir/all] Error 2
make[1]: Leaving directory `/home/jason/test'
make: *** [all] Error 2
[jason@localhost test]$

**Comment by JasonDictos** [comment]
I had to manually add an include for that path, is there a better way? Thought it would just inherit its config:

cmake_minimum_required(VERSION 3.10.2 FATAL_ERROR)

set(HUNTER_TLS_VERIFY off)

include(cmake/HunterGate.cmake)
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.238.tar.gz"
        SHA1 "9e103596184adb7206430047375a07eb1fa6a9b4"
)

project(BrtCommon)

hunter_add_package(intsizeof)
find_package(intsizeof CONFIG REQUIRED)

add_executable(Test test.c)
include_directories("/home/jason/.hunter/_Base/9e10359/45e2ab9/cdc17dc/Install/include")

target_link_libraries(Test intsizseof)
~                                                                                                                                                                                                                                   
~

**Comment by JasonDictos** [comment]
Some more info:
[jason@localhost test]$ ./Test 
SIZE_MAX: 18446744073709551615
UINT8_MAX: 255
UINT16_MAX: 65535
UINT32_MAX: 4294967295
UINT64_MAX: 18446744073709551615
[jason@localhost test]$ 

test.c:
#include <stdint.h> // PTRDIFF_MIN
#include <limits.h> // CHAR_BIT
#include <stdio.h>

int main()
{
        printf("SIZE_MAX: %llu\n", SIZE_MAX);
        printf("UINT8_MAX: %llu\n", UINT8_MAX);
        printf("UINT16_MAX: %llu\n", UINT16_MAX);
        printf("UINT32_MAX: %llu\n", UINT32_MAX);
        printf("UINT64_MAX: %llu\n", UINT64_MAX);
        return 0;
}

**Comment by JasonDictos** [comment]
Ok so LLONG_MAX isn't defined thats the prob looks like. Must be this old centos runtime.

**Comment by JasonDictos** [comment]
It appears in my limits.h file, the LLONG_MAX block is conditionally gated with:

/* If we are not using GNU CC we have to define all the symbols ourself.
   Otherwise use gcc's definitions (see below).  */
#if !defined __GNUC__ || __GNUC__ < 2

**Comment by JasonDictos** [comment]
Ah so adding '__USE_ISOC99' definition fixes it:


#include <stdint.h> // PTRDIFF_MIN
#define __USE_ISOC99
#include <limits.h> // CHAR_BIT
#include <stdio.h>
#include <intsizeof.h>

int main()
{
        printf("LLONG_MAX: %llu\n", LLONG_MAX);
        printf("UINT8_MAX: %llu\n", UINT8_MAX);
        printf("UINT16_MAX: %llu\n", UINT16_MAX);
        printf("UINT32_MAX: %llu\n", UINT32_MAX);
        printf("UINT64_MAX: %llu\n", UINT64_MAX);
        return 0;
}

**Comment by JasonDictos** [comment]
Whats the best way to set such a definition in the hunter ecosystem from the client api?

**Comment by JasonDictos** [comment]
This also fixes it:

target_compile_features(Test PUBLIC c_std_99)

**Comment by JasonDictos** [comment]
Ok well I got this working by setting -std=c99 in the toolchain. Donnou if this is an issue that really matters as this is an ancient setup we build our tools on for backwards abi compatibility.

**Comment by JasonDictos** [comment]
This fixed it for me:

hunter_config(CURL VERSION 7.49.1-DEV-v9
    CMAKE_ARGS HTTP_ONLY=On
    CMAKE_ARGS CMAKE_C_FLAGS=-std=c99
)

**Comment by JasonDictos** [comment]
Alright well here's the final config call that got me working:

    hunter_config(CURL VERSION 7.49.1-DEV-v9
        CMAKE_ARGS
            HTTP_ONLY=On
            CMAKE_C_FLAGS=-std=c99\ -fPIC\ -D__USE_ISOC99=1\ -D__USE_POSIX=1\ -D_GNU_SOURCE=1
    )

**Comment by ruslo** [comment]
> set(HUNTER_TLS_VERIFY off)

See https://docs.hunter.sh/en/latest/reference/user-variables.html#cmake

> Ok, got it working with 'lowercase' intsizeof

Always check https://docs.hunter.sh/en/latest/packages/pkg/intsizeof.html

> Ok so LLONG_MAX isn't defined thats the prob looks like

I've added a check:

* https://github.com/ruslo/intsizeof/blob/d2c974787abebed1df4ce5eac270e3a8e65d450c/lib/intsizeof.h#L44-L46

> Whats the best way to set such a definition in the hunter ecosystem from the client api?

Depends on type of definition

> -std=c99\ -fPIC\ -D__USE_ISOC99=1\ -D__USE_POSIX=1\ -D_GNU_SOURCE=1

That's a global flags, really belongs to toolchains, not to particular package.

Also feel free to add notes to https://github.com/ruslo/intsizeof#hints
