### ISSUE TITLE
Cannot open include file: 'stdint.h': No such file or directory

### ISSUE THREAD

**Issue by ikerr** [ruslo/intsizeof#2]
While trying to compile CURL using the Windows v6.1 SDK, I get the following error, related to intsizeof:

C:\.hunter\_Base\b461620\d027a34\eaa6138\Install\include\intsizeof.h(7) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

More information here: https://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

I wonder if it would be easy to support instances where stdint.h is not available.

**Comment by ruslo** [comment]
> More information here: https://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

> While trying to compile CURL using the Windows v6.1 SDK

The question is 10 years old, same with SDK version. Can you just upgrade Visual Studio?

**Comment by ikerr** [comment]
Thanks. Yes, I updated to the latest version of Visual Studio and the problem went away. I guess it's a bit much to ask to support versions that old :) Feel free to disregard, and thanks for the great tool!
